language: java
jdk:
- oraclejdk8

sudo: false

before_script:
- npm install
- bower install

script:
- mvn package -Popenshift

after_success:
- sed -i '/bower_components\//d' .gitignore
- git config --global user.email "travis@localhost.localdomain"
- git config --global user.name "Travis CI"
- git checkout $TRAVIS_BRANCH
- git add --all
- git commit -am "Travis build $TRAVIS_BUILD_NUMBER"

deploy:
  skip_cleanup: true
  provider: openshift
  user: $OPENSHIFT_USERNAME
  password: $OPENSHIFT_PASSWORD
  app: clubby
  domain: teamasdasd
  on:
    repo: Tony-Mc/asdasd
    branch: master
