language: java
jdk:
- oraclejdk8

sudo: false

before_script:
- nvm install 5.10.0
- nvm use 5.10.0
- cd src/main/webapp # jump to package.json
- npm install
- npm run build
- cd ../../.. # jump back to root

script:
- mvn package -Popenshift

before_deploy:
- git config --global user.email "travis@localhost.localdomain"
- git config --global user.name "Travis CI"
- git checkout $TRAVIS_BRANCH
- sed -i '/src\/main\/webapp\/node_modules\//d' .gitignore
- sed -i '/src\/main\/webapp\/dist\//d' .gitignore
- git add src/main/webapp/dist/vendor.bundle.js
- git add src/main/webapp/dist/app.bundle.js
- git add src/main/webapp/node_modules/angular2/bundles/angular2-polyfills.js
- git add src/main/webapp/node_modules/jquery/dist/jquery.js
- git add src/main/webapp/node_modules/bootstrap/dist/js/bootstrap.js
- git commit -am "Travis build $TRAVIS_BUILD_NUMBER"

deploy:
  skip_cleanup: true
  provider: openshift
  user: $OPENSHIFT_USERNAME
  password: $OPENSHIFT_PASSWORD
  app: clubby
  domain: teamasdasd
  on:
    repo: Tony-Mc/asdasd
    branch: master
