language: java
jdk:
- oraclejdk8
sudo: false
before_script:
- npm install
- bower install
script:
- mvn package -Popenshift
deploy:
  skip_cleanup: true
  
  provider: openshift
  user: $OPENSHIFT_USERNAME
  password: $OPENSHIFT_PASSWORD
  app: clubby
  domain: teamasdasd
  on:
    repo: Tony-Mc/asdasd
    branch: master
